import Car from './car.js';
import ParkingLot from './parkingLot.js';

const car = new Car('ABC-123', 'whIte');
const car2 = new Car('GHJ-355', 'red');
const car3 = new Car('GHJ-356', 'WHITE');
const car4 = new Car('RTA-353', 'white');
const car5 = new Car('JUT-351', 'black');
const car6 = new Car('FIS-356', 'BLACK');
const parkingLot = new ParkingLot();

// console.log(car);
console.log(parkingLot.create(4));
console.log(parkingLot.parkCar(car));
console.log(parkingLot.parkCar(car2));
console.log(parkingLot.parkCar(car3));
console.log(parkingLot.parkCar(car4));
console.log(parkingLot.parkCar(car5));
console.log(parkingLot.parkCar(car6));
console.log();
console.log(parkingLot.getRegistrationNumbersByColor('purple'));
console.log(parkingLot.getRegistrationNumbersByColor('Black'));
console.log(parkingLot.getRegistrationNumbersByColor('WHITE'));
console.log();
console.log(parkingLot.getTicketNumberByRegistrationNumber('ABC-123'));
console.log(parkingLot.getTicketNumberByRegistrationNumber('rry-531'));
console.log();
console.log(parkingLot.getTicketNumbersByColor('white'));
console.log(parkingLot.getTicketNumbersByColor('purple'));
console.log(parkingLot.getTicketNumbersByColor('black'));
